#!/usr/bin/env python3
# -*- coding: utf-8 -*-


"""
Testing Schema reg
"""

from ..utils import schreg_get_all_schemas, schreg_get_versions

def test_schema_registry_schemas():
    schemas = schreg_get_all_schemas()
    assert len(schemas) == 1
    schema_meta = schemas[0]['schemaMetadata']
    assert schema_meta['evolve'] == True
    assert schema_meta['description'] == 'Schema for the data generated by the IoT sensors'
    assert schema_meta['schemaGroup'] == 'Kafka'
    assert schema_meta['type'] == 'avro'
    assert schema_meta['compatibility'] == 'BACKWARD'
    assert schema_meta['validationLevel'] == 'ALL'
    assert schema_meta['name'] == 'SensorReading'

def test_schema_registry_versions():
    versions = schreg_get_versions('SensorReading')
    assert len(versions) == 1
    version = versions[0]
    assert version['name'] == 'SensorReading'
    assert version['version'] == 1
    assert version['stateId'] == 5
    assert len(version['schemaText']) == 1847
